//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaAdvertisingApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Программа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Программа()
        {
            this.Заказчик = new HashSet<Заказчик>();
            this.Сотрудник = new HashSet<Сотрудник>();
        }
    
        public int Программа_ID { get; set; }
        public string Название_программы { get; set; }
        public Nullable<int> Рейтинг { get; set; }
        public Nullable<System.TimeSpan> Время_рекламных_блоков { get; set; }
        public Nullable<decimal> Стоимость_минуты { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказчик> Заказчик { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудник> Сотрудник { get; set; }

        internal void Add(Программа selectedProgram)
        {
            throw new NotImplementedException();
        }

        internal void Remove(Программа selectedProgram)
        {
            throw new NotImplementedException();
        }
    }
}
