//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaAdvertisingApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public int Сотрудник_ID { get; set; }
        public string ФИО_сотрудника { get; set; }
        public string Должность { get; set; }
        public Nullable<int> ID_заказчика { get; set; }
        public Nullable<int> ID_программы { get; set; }
    
        public virtual Заказчик Заказчик { get; set; }
        public virtual Программа Программа { get; set; }
    }
}
